const USER_ROLES = Object.freeze({
  ATHLETE: "ATHLETE",
  CLUB: "CLUB",
  ACADEMY: "ACADEMY",
  AGENCY: "AGENCY",
  SCOUT: "SCOUT",
  ADMIN: "ADMIN",
});

const ACCOUNT_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  SUSPENDED: "SUSPENDED",
  DEACTIVATED: "DEACTIVATED",
  PENDING: "PENDING",
});

const VERIFICATION_STATUS = Object.freeze({
  NOT_SUBMITTED: "NOT_SUBMITTED",
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
});

const VERIFICATION_TYPES = Object.freeze({
  IDENTITY: "IDENTITY",
  ATHLETE: "ATHLETE",
  ORGANIZATION: "ORGANIZATION",
  CERTIFICATE: "CERTIFICATE",
});

const OPPORTUNITY_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  CLOSED: "CLOSED",
  CANCELLED: "CANCELLED",
});

const APPLICATION_STATUS = Object.freeze({
  APPLIED: "APPLIED",
  SHORTLISTED: "SHORTLISTED",
  TRIAL_INVITED: "TRIAL_INVITED",
  SELECTED: "SELECTED",
  REJECTED: "REJECTED",
  WITHDRAWN: "WITHDRAWN",
});

export {
  USER_ROLES,
  ACCOUNT_STATUS,
  VERIFICATION_STATUS,
  VERIFICATION_TYPES,
  OPPORTUNITY_STATUS,
  APPLICATION_STATUS,
};